In [1]:
from IPython.display import display, HTML
display(HTML("""
<style>
div.container{width:99% !important;}
div.cell.code_cell.rendered{width:100%;}
div.input_prompt{padding:0px;}
div.CodeMirror {font-family:Consolas; font-size:22pt;}
div.text_cell_render.rendered_html{font-size:18pt;}
div.text_cell_render ul li{font-size:22pt; line-height:30px;}
div.output {font-size:22pt; font-weight:bold;}
div.input {font-family:Consolas; font-size:22pt;}
div.prompt {min-width:70px;}
div#toc-wrapper{padding-top:120px;}
div.text_cell_render ul li{font-size:22pt;padding:5px;}
table.dataframe{font-size:22px;}
</style>
"""))

# 1. tensorfldw v2.xx에서 v1사용하기
- 

In [8]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior() # tensorflow V2 비활성화하고 v1활성화
import numpy as np
import pandas as pd

Instructions for updating:
non-resource variables are not supported in the long term


## Tensorflw
- 데이터 흐름 그래프(tensor 객체 흐름)을 사용하는 수치 계산 라이브러리
- 그래프는 node(연산)와 edge로 구성
- sess = tf.Session()을 이용해서 실행 환경
- sess.run()을 통해서 실행 결과를 확인

In [9]:
# 1단계 : tensor(상수 노드 하나) 정의
node1 = tf.constant('Hello, Tensorflow')
# 2단계 : 세션(연산을 실행하는 환경) 생성
sess = tf.Session()
# 3단계 : 실제 실행 및 출력
print(sess.run(node1))
print(sess.run(node1).decode())

b'Hello, Tensorflow'
Hello, Tensorflow


In [10]:
# 간단한 연산 tensor 그래프
# 1. 그래프 정의
node1 = tf.constant(10, dtype=tf.float16)
node2 = tf.constant(20, dtype=tf.float16)
node3 = tf.add(node1, node2)
# 2. 세션 생성
sess = tf.Session()
# 3. 세션 실행 & 결과 
print(sess.run([node1, node2, node3]))

[10.0, 20.0, 30.0]


In [11]:
# 타입변경
import numpy as np
node1 = tf.constant(np.array([1,2,3]), dtype=tf.int16)
node2 = tf.cast(node1, dtype=tf.float32)
sess = tf.Session()
print(sess.run([node1, node2]))

[array([1, 2, 3], dtype=int16), array([1., 2., 3.], dtype=float32)]


In [12]:
# 평균값 계산 : tf.reduce_mean()
data = np.array([1.,2.,3.,4.])
m = tf.reduce_mean(data)
sess = tf.Session()
print(sess.run(m))

2.5


In [13]:
# tf.random_normal([size]) : 평균이 0이고 표준편차가 1인 난수 size개 발생
w = tf.random_normal([3]) 
sess = tf.Session()
sess.run(w)

array([-0.24455708,  1.9588145 ,  1.2719293 ], dtype=float32)

In [14]:
#  변수 노드
w = tf.Variable(tf.random_normal([1]))
sess = tf.Session()
sess.run(tf.global_variables_initializer()) # 변수 초기화
sess.run(w)

array([-0.85789114], dtype=float32)

# 2 tensorflow v1을 이용한 회귀분석 구현
2.1 독립변수 x가 1개, 타겟(종속)변수 y가 1개

In [15]:
# tensor 그래프 정의
# 데이터 셋 확보
x = np.array([1,2,3])
y = np.array([2,3,4])
# weight와 bias
W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse )
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 W, b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 곡선위 미분값이 0이 되는 방향
(경사하강법GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W, b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b])
    if step%300==0:
        print("{}번째 cost:{}, W:{}, b:{}".format(step, cost_val, W_val, b_val))

0번째 cost:2.648893117904663, W:[1.0298967], b:[-0.52339554]
300번째 cost:0.05637480318546295, W:[1.2751017], b:[0.37462938]
600번째 cost:0.013302129693329334, W:[1.1336323], b:[0.6962225]
900번째 cost:0.0031387803610414267, W:[1.064913], b:[0.85243773]
1200번째 cost:0.0007406205986626446, W:[1.0315318], b:[0.92832094]
1500번째 cost:0.00017475963977631181, W:[1.0153168], b:[0.9651812]
1800번째 cost:4.123623148188926e-05, W:[1.0074403], b:[0.98308647]
2100번째 cost:9.730488272907678e-06, W:[1.0036143], b:[0.991784]
2400번째 cost:2.296450702488073e-06, W:[1.0017558], b:[0.9960086]
2700번째 cost:5.424970481726632e-07, W:[1.0008535], b:[0.99806017]
3000번째 cost:1.2841826446674531e-07, W:[1.0004153], b:[0.99905616]
3300번째 cost:3.054012154279917e-08, W:[1.0002028], b:[0.9995399]
3600번째 cost:7.321640627111492e-09, W:[1.0000994], b:[0.99977475]
3900번째 cost:1.797071491616009e-09, W:[1.0000491], b:[0.9998884]
4200번째 cost:4.203949688363906e-10, W:[1.0000237], b:[0.999946]
4500번째 cost:1.2259586401608402e-10, W:[1.0000

In [18]:
# 최종적으로 나온 회귀식 H = W*x + b
W_, b_ = sess.run([W, b])

In [19]:
W_, b_

(array([1.0000087], dtype=float32), array([0.9999811], dtype=float32))

In [20]:
def predict(x):
    return W_[0] * x + b_[0]

In [21]:
predict(5)

6.000024616718292

# 2.2 predict을 위한 placeholder 이용
- placeholder: 외부에서 데이터를 입력받을 수 있는 노드

In [22]:
x = tf.placeholder(dtype=tf.float32)
H = 1*x + 1
sess = tf.Session()
sess.run([x, H], feed_dict={x : np.array([40,50])})

[array([40., 50.], dtype=float32), array([41., 51.], dtype=float32)]

In [23]:
# tensor 그래프 정의
# 데이터 셋 확보
x_data = np.array([1,2,3])
y_data = np.array([2,3,4])
# placeholder 설정(x, y)
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight와 bias
W = tf.Variable(tf.random.normal([1]), name='weight')
b = tf.Variable(tf.random.normal([1]), name='bias')
# Hat, Hypothesis : 결과는 numpy 배열
H = W * x + b
# cost function (손실함수 : mse )
cost = tf.reduce_mean(tf.square(H-y))
'''
학습목적 : cost가 최소가 되는 W, b를 찾는 것
cost 함수는 2차함수이므로 곡선 그래프. 곡선위 미분값이 0이 되는 방향
(경사하강법GradientDescent)
'''
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# 세션 생성
sess = tf.Session()
# W, b 초기화
sess.run(tf.global_variables_initializer())
# 6000번 학습 (v2 에서의 fit함수)
for step in range(6001):
    _, cost_val, W_val, b_val = sess.run([train, cost, W, b],
                                        feed_dict={x:x_data,
                                                   y:y_data})
    if step%300==0:
        print("{}번째 cost:{}, W:{}, b:{}".format(step, cost_val, W_val, b_val))

0번째 cost:18.026288986206055, W:[-1.0091741], b:[1.611886]
300번째 cost:0.05341898277401924, W:[0.7322074], b:[1.6087554]
600번째 cost:0.012604750692844391, W:[0.8699179], b:[1.2957072]
900번째 cost:0.0029741900507360697, W:[0.9368119], b:[1.1436411]
1200번째 cost:0.0007017938769422472, W:[0.9693058], b:[1.069775]
1500번째 cost:0.00016558817878831178, W:[0.98509043], b:[1.033893]
1800번째 cost:3.9076359826140106e-05, W:[0.9927572], b:[1.0164645]
2100번째 cost:9.219970706908498e-06, W:[0.9964819], b:[1.0079975]
2400번째 cost:2.1753703549620695e-06, W:[0.9982911], b:[1.0038847]
2700번째 cost:5.134025400366227e-07, W:[0.9991698], b:[1.0018873]
3000번째 cost:1.2130006155075534e-07, W:[0.99959624], b:[1.0009174]
3300번째 cost:2.8861165901616914e-08, W:[0.9998032], b:[1.0004474]
3600번째 cost:6.948482678126311e-09, W:[0.99990356], b:[1.0002196]
3900번째 cost:1.7276798880416777e-09, W:[0.999952], b:[1.0001097]
4200번째 cost:4.61758048464489e-10, W:[0.9999753], b:[1.0000567]
4500번째 cost:8.710306781400945e-11, W:[0.9999891

In [24]:
# 예측하기
sess.run(H,feed_dict={x:5})

array([5.9999704], dtype=float32)

## 2.3 scale이 다른 데이터들의 회귀분석 구현(scale 조정x)

In [25]:
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost (손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)
train = optimizer.minimize(cost)
# Session & 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:x_data, y:y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step+1, cost_val))

301/6000번째 cost:114.23582458496094
601/6000번째 cost:79.69474792480469
901/6000번째 cost:79.38969421386719
1201/6000번째 cost:79.37847137451172
1501/6000번째 cost:79.37005615234375
1801/6000번째 cost:79.36198425292969
2101/6000번째 cost:79.35417175292969
2401/6000번째 cost:79.34661865234375
2701/6000번째 cost:79.33938598632812
3001/6000번째 cost:79.33236694335938
3301/6000번째 cost:79.3255615234375
3601/6000번째 cost:79.3190689086914
3901/6000번째 cost:79.31275177001953
4201/6000번째 cost:79.30667877197266
4501/6000번째 cost:79.30082702636719
4801/6000번째 cost:79.29515075683594
5101/6000번째 cost:79.28968048095703
5401/6000번째 cost:79.28443145751953
5701/6000번째 cost:79.27933502197266
6001/6000번째 cost:79.27442169189453


## 2.4 scale이 다른 데이터드의 회귀분석 구현(scale 조정 ㅇ)
### scale 조정방법: 모든 데이터를 일정 범위내로 조정
- normalization(정규화): 모든 데이터를 0~1 사이로 조정
                     X-Xmin
- normalization=  ─────────────────────────
                     Xmax  - Xmin
       * 위의 식을 써도 되지마 라이브러리(MinMaxScsler)를 주로 씀
- standarization(표준화): 데이터의 평균을 0, 표준편차를 1로 조정
                    X-Xmean
- standarization=  ─────────────────────────
                     Xstd(표준편차)
       * 위의 식보다 라이브러리 추천(sklearn.preprocessing.StandardScaler)  
                  

In [27]:
# 라이브러리 쓰지 않고 정규화
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# x_data.min(), x_data.max(), x_data.mean(), x_data.std()
norm_scaled_x_data = (x_data - x_data.min()) / (x_data.max() - x_data.min())
norm_scaled_y_data = (y_data - y_data.min()) / (y_data.max() - y_data.min())

In [28]:
# 라이브러리를 사용하여 정규화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)
from sklearn.preprocessing import MinMaxScaler
scaler_x = MinMaxScaler() # 독립변수 x를 정규화시킬 객체
scaler_x.fit(x_data)
norm_scaled_x_data = scaler_x.transform(x_data)
scaler_y = MinMaxScaler() # 종속(타겟)변수 y를 정규화시킬 객체
norm_scaled_y_data = scaler_y.fit_transform(y_data)
norm_scaled_y_data

array([[0.        ],
       [0.11111111],
       [0.7       ],
       [0.83333333],
       [1.        ]])

In [29]:
# 라이브러리 쓰지 않고 표준화
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
stan_scaled_x_data = (x_data - x_data.mean()) / x_data.std()
stan_scaled_y_data = (y_data - y_data.mean()) / y_data.std()
np.column_stack([x_data, norm_scaled_x_data, stan_scaled_x_data])

array([[ 1.        ,  0.        , -1.22474487],
       [ 2.        ,  0.11111111, -0.93313895],
       [ 5.        ,  0.44444444, -0.05832118],
       [ 8.        ,  0.77777778,  0.81649658],
       [10.        ,  1.        ,  1.39970842]])

In [31]:
np.column_stack([y_data, norm_scaled_y_data, stan_scaled_y_data])

array([[ 5.        ,  0.        , -1.32373476],
       [15.        ,  0.11111111, -1.04563922],
       [68.        ,  0.7       ,  0.42826713],
       [80.        ,  0.83333333,  0.76198177],
       [95.        ,  1.        ,  1.17912508]])

In [33]:
# 라이브러리를 사용하여 표준화
x_data = np.array([1, 2, 5, 8, 10]).reshape(-1,1)
y_data = np.array([5, 15, 68, 80, 95]).reshape(-1,1)

from sklearn.preprocessing import StandardScaler
scaler_x=StandardScaler()
stan_scaled_x_data=scaler_x.fit_transform(x_data)
scaler_y=StandardScaler()
stan_scaled_y_data=scaler_y.fit_transform(y_data)

In [34]:
# 스케일 조정된 데이터를 다시 복구 : inverse_transform() 이용
scaler_y.inverse_transform(stan_scaled_y_data)

array([[ 5.],
       [15.],
       [68.],
       [80.],
       [95.]])

In [35]:
x_data = np.array([1, 2, 5, 8, 10])
y_data = np.array([5, 15, 68, 80, 95])
# placeholder 설정
x = tf.placeholder(dtype=tf.float32)
y = tf.placeholder(dtype=tf.float32)
# weight & bias
W = tf.Variable(tf.random.normal([1]))
b = tf.Variable(tf.random.normal([1]))
# Hypothesis
H = W * x + b
# cost (손실함수)
cost = tf.reduce_mean(tf.square(H-y))
# 경사하강법
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.01)
train = optimizer.minimize(cost)
# Session & 변수 초기화
sess = tf.Session()
sess.run(tf.global_variables_initializer())
# 학습
for step in range(1, 6001):
    _, cost_val = sess.run([train, cost], feed_dict={x:norm_scaled_x_data, 
                                                     y:norm_scaled_y_data})
    if step%300==0:
        print("{}/6000번째 cost:{}".format(step, cost_val))

300/6000번째 cost:0.1443975269794464
600/6000번째 cost:0.04299086704850197
900/6000번째 cost:0.017967844381928444
1200/6000번째 cost:0.011793127283453941
1500/6000번째 cost:0.01026945747435093
1800/6000번째 cost:0.009893473237752914
2100/6000번째 cost:0.009800698608160019
2400/6000번째 cost:0.009777804836630821
2700/6000번째 cost:0.00977215263992548
3000/6000번째 cost:0.00977076031267643
3300/6000번째 cost:0.009770412929356098
3600/6000번째 cost:0.009770331904292107
3900/6000번째 cost:0.009770309552550316
4200/6000번째 cost:0.009770305827260017
4500/6000번째 cost:0.009770303964614868
4800/6000번째 cost:0.009770304895937443
5100/6000번째 cost:0.009770306758582592
5400/6000번째 cost:0.009770302101969719
5700/6000번째 cost:0.009770302101969719
6000/6000번째 cost:0.009770302101969719
